### ISSUE TITLE
Recently broken/outdated?

### ISSUE THREAD

**Issue by Aypac** [adafruit/ci-arduino#147]
I have been using this repo for a long while.
It used to work rather well: [build from 02-Dec-2022](https://app.travis-ci.com/github/Aypac/Arduino-TR-064-SOAP-Library/builds/258431296). However, if I now re-run that same build it gives me and error: [re-run same build from 11-Jan-2023](https://app.travis-ci.com/github/Aypac/Arduino-TR-064-SOAP-Library/builds/259304400). I have not changed anything on my side in the meantime.

I see the following error-messages:
```
Collecting adafruit-nrfutil
  Downloading adafruit-nrfutil-0.5.3.post16.tar.gz (49 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tFGJYj/adafruit-nrfutil/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tFGJYj/adafruit-nrfutil/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-mI_iWG
         cwd: /tmp/pip-install-tFGJYj/adafruit-nrfutil/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-tFGJYj/adafruit-nrfutil/setup.py", line 90, in <module>
        with open(os.path.join(here, 'README.md'), encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
```
Later I then get:
```
fork/exec {runtime.tools.python3.path}/python3: no such file or directory
```

I will investigate further later, but I would appreciate any help in the meantime.

**Comment by brentru** [comment]
I just ran ci-arduino on a new Linux runner and was not able to replicate this issue. The issue seems to be with the installation of adafruit-nrfutil, not this library. Please try installing Python 3, Python 2 is outdated, and trying to re-run this script again.
